#!/bin/bash
set -u

STAMP="$(date +%Y%m%d-%H%M%S)"
OUT="$HOME/Desktop/RTXMac-Diagnostics-$STAMP"
mkdir -p "$OUT"

run_capture() {
  local name="$1"
  shift
  {
    echo "$ $*"
    "$@"
  } >"$OUT/$name.txt" 2>&1 || true
}

run_capture system_profiler system_profiler SPDisplaysDataType SPPCIDataType
run_capture system_extensions systemextensionsctl list
run_capture boot_args sysctl kern.bootargs
run_capture ioreg_rtxmac sh -c 'ioreg -l -w0 -p IOService | grep -Ei "rtxmac|10de|2489|display|IOPCIDevice"'
run_capture dmar sh -c 'ioreg -l -w0 -p IODeviceTree | grep -i -C 8 "DMAR"'
run_capture rtxmac_log log show --last 30m --style compact --predicate 'eventMessage CONTAINS[c] "rtxmac"'

cat >"$OUT/README.txt" <<'EOF'
RTXMac diagnostic bundle.
Generated by the read-only prototype collection script.
No NVRAM dump, browser data, personal documents, or credentials are collected.
EOF

ZIP="$OUT.zip"
/usr/bin/ditto -c -k --sequesterRsrc --keepParent "$OUT" "$ZIP"
echo "Diagnostics written to: $ZIP"
